apiVersion: v1
kind: Service
metadata:
  name: callme-service
  labels:
    app: callme-service
spec:
  # type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app: callme-service
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: callme-service
spec:
  gateways:
    - callme-gateway
  hosts:
    - "callme.example.com"
  http:
    - route:
        - destination:
            host: "callme-service"
