apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: simple-istio-services
build:
  artifacts:
    - image: caller-service
      jib:
        project: caller-service
        args:
          - -Pjib
          - -DskipTests
    - image: callme-service
      jib:
        project: callme-service
        args:
          - -Pjib
          - -DskipTests
  local:
    push: true
    useBuildkit: true
  tagPolicy:
    customTemplate:
      template: "{{.TIME}}_{{.GIT_HASH}}"
      components:
      - name: TIME
        dateTime:
          format: "2006-01-02"
          timezone: "UTC"
      - name: GIT_HASH
        gitCommit:
          variant: AbbrevCommitSha
# manifests:
#   rawYaml:
#     - '*/k8s/deployment.yaml'
# deploy:
#   kubectl: {}
# profiles:
#   - name: istio
#     manifests:
#       rawYaml:
#         - k8s/istio-*.yaml
#         - '*/k8s/deployment-versions.yaml'
#         - '*/k8s/istio-*.yaml'
