apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
  - image: callme-service
    context: Dockerfile
    jib:
      args:
        - -Pjib
  tagPolicy:
    customTemplate:
      template: "{{.FOO}}_{{.BAR}}"
      components:
      - name: FOO
        dateTime:
          format: "2006-01-02"
          timezone: "UTC"
      - name: BAR
        gitCommit:
          variant: AbbrevCommitSha
