apiVersion: v1
kind: ServiceAccount
metadata:
  name: caller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caller-service
  template:
    metadata:
      name: caller-service
      labels:
        app: caller-service
        version: v1
    spec:
      serviceAccountName: caller
      containers:
      - name: caller-service
        image: maxjerin/caller-service:2023-11-02_6c71c8e-dirty
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_APPLICATION_VERSION
            value: "v1"
          - name: SPRING_APPLICATION_DEPENDENCIES_CALLME_HOST
            value: "callme-service"
          - name: SPRING_APPLICATION_DEPENDENCIES_CALLME_PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: caller-service
  labels:
    app: caller-service
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: caller-service
