apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: caller-gateway
spec:
  selector:
    istio: eastwestgateway
  servers:
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: caller-service-destination
spec:
  host: caller-service
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: caller-service
spec:
  hosts:
    - "*"
  gateways:
    - caller-gateway
  http:
    - route:
        - destination:
            host: caller-service
            port:
              number: 8080
